TestWeb/Models/OrderViewModels/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Trainee.Business.DAL.Entities;

namespace Eshop2.Models.OrderViewModels
{
    public class CartViewModel
    {
        public List<CartItem> Cart { get; set; }

    }
}

TestWeb/Models/OrderViewModels/OrderViewModel.cs
using Eshop2.Models.Validations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Trainee.Business.DAL.Entities;
using Trainee.Core.DAL.Entities;

namespace Eshop2.Models.OrderViewModels
{
    public class OrderViewModel
    {
        [Required(ErrorMessage = "Prosím vyplňte e-mail.")]
        [EmailAddress(ErrorMessage = "Prosím vyplňte validní e-mail.")]
        [Display(Name = "E-mail")]
        public string Email { get; set; }


        [Display(Name = "Jméno")]
        [Required(ErrorMessage = "Prosím vyplňte své jméno.")]
        public string Name { get; set; }
        
        [Display(Name = "Příjmení")]
        [Required(ErrorMessage = "Prosím vyplňte své příjmení.")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "Prosím vyplňte telefon.")]
        [Display(Name = "Telefon")]
        [Phone(ErrorMessage = "Prosím vyplňte telefonní číslo.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Prosím vyplňte ulici.")]
        [Display(Name = "Ulice")]
        public string Street { get; set; }

        [Required(ErrorMessage = "Prosím vyplňte PSČ.")]
        [Display(Name = "PSČ")]
        [MaxLength(50, ErrorMessage = "Prosím vyplňte PSČ.")]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "Prosím vyplňte město.")]
        [Display(Name = "Město")]
        public string City { get; set; }

        [Display(Name = "Stát")]
        [Required(ErrorMessage = "Prosím vyberte zemi.")]
        public int CountryId { get; set; }


        [Required(ErrorMessage = "Vyberte prosím způsob platby.")]
        public int PaymentId { get; set; }

        [Required(ErrorMessage = "Vyberte prosím způsob dopravy.")]
        public int ShippingId { get; set; }

        [IsTrue(ErrorMessage = "Prosím potvrďte souhlas s obchodními podmínkami.")]
        public bool IsChecked { get; set; }

        public List<Payment> Payment { get; set; }
        public List<Shipping> Shipping { get; set; }
        public List<CartItem> Items { get; set; }
        public List<Country> Countries { get; set; }





    }
}

TestWeb/Controllers/CatalogueController.cs
using Alza.Core.Identity.Dal.Entities;
using Eshop2.Abstraction;
using Eshop2.Models.CatalogueViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Trainee.Business.Business;
using Trainee.Business.Business.Enums;
using Trainee.Business.Business.Wrappers;
using Trainee.Business.DAL.Entities;
using Trainee.Catalogue.Business;
using Trainee.Catalogue.DAL.Entities;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Eshop2.Controllers
{
    /// <summary>
    /// This controller provides a list of products and book details
    /// </summary>
    public class CatalogueController : Controller
    {
        private readonly BusinessService _businessService;
        private readonly CatalogueService _catalogueService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly BookLoader _bookLoader;

        public CatalogueController(BusinessService businessService, CatalogueService catService, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _businessService = businessService;
            _catalogueService = catService;
            _signInManager = signInManager;
            _userManager = userManager;
            _bookLoader = new BookLoader(businessService);
        }



        // GET: /Catalogue/Book/BookId
        [HttpGet("/Catalogue/Book/{id?}")]
        public IActionResult Book(int? id)
        {
            try
            {
                //book id missing
                if (id == null)
                {
                    return RedirectToAction("Error", "Home");
                }



                ViewData["productId"] = id;

                BookViewModel model = _bookLoader.LoadBookModel(id.Value);

                var cat = _catalogueService.GetCategory(model.Category.ParentId.Value);
                if (cat.isOK && !cat.isEmpty)
                    model.Category.Parent = cat.data;

                if (model == null)
                    return RedirectToAction("Error", "Home");


                //to be sure //Or handle it in view
                model.Reviews = model.Reviews == null ? new List<Review>() : model.Reviews;

                return View(model);
            }
            catch (Exception e)
            {
                return AlzaError.ExceptionActionResult(e);
            }
        }
        // POST: /Catalogue/Book/{id}
        [HttpPost("/Catalogue/Book/{id}")]
        public async Task<IActionResult> Book(int? id, BookViewModel model)
        {
            try
            {
                //to add a review, user must be signed in
                if (!_signInManager.IsSignedIn(User))
                    return RedirectToAction("Login", "Account", new { returnUrl = $"/Catalogue/Book/{id}" });

                if (id == null)
                {
                    return RedirectToAction("Error", "Home");
                }

                if (_businessService.GetProduct(id.Value) == null)
                    return RedirectToAction("Error", "Home");

                model.ProductId = id.Value;



                var user = await _userManager.GetUserAsync(User);

                ViewData["productId"] = id;


                Review review = new Review
                {
                    Date = DateTime.Now,
                    ProductId = model.ProductId,
                    Rating = model.NewRating,
                    Text = model.ReviewText,
                    UserId = user.Id
                };

                //review can be added only if there is no other 
                if (_businessService.GetReview(review.UserId, review.ProductId).isEmpty)
                {
                    _businessService.AddReview(review);
                }

                model = _bookLoader.LoadBookModel(id.Value);


                return View(model);
            }
            catch (Exception e)
            {
                return AlzaError.ExceptionActionResult(e);
            }
        }



        // GET: /Catalogue/Products/{id?}
        [HttpGet("/Catalogue/Products/{id?}")]
        public IActionResult Products(int? id, int? pageNum, ProductsViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Default category is the first one (all items)
                    if (id == null)
                    {
                        id = 1;
                    }
                    int catId = id.Value;

                    model.currentCategory = _catalogueService.GetCategory(catId).data;

                    //Unknown category id
                    if (model.currentCategory == null)
                    {
                        return RedirectToAction("Error", "Home");
                    }

                    //First page is default
                    if (model.PageNum == null)
                    {
                        model.PageNum = pageNum == null ? 1 : pageNum;
                    }

                    //creating the wrapper from filtering data
                    QueryParametersWrapper parameters = new QueryParametersWrapper
                    {
                        PageNum = model.PageNum.Value,
                        CategoryId = catId,
                        MaxPrice = model.MaxPriceFilter,
                        MinPrice = model.MinPriceFilter,
                        PageSize = model.PageSize,
                        SortingParameter = model.SortingParameter,
                    };

                    //custom filtering
                    if(model.SortingType == null)
                    {
                        switch (model.SortingParameter)
                        {
                            case SortingParameter.Date:
                            case SortingParameter.Rating:
                                parameters.SortingType = SortType.Desc;
                                break;
                            case SortingParameter.Name:
                            case SortingParameter.Price:
                                parameters.SortingType = SortType.Asc;
                                break;

                            default:
                                parameters.SortingType = SortType.Asc;
                                break;
                        }
                    }
                    else
                    {
                        parameters.SortingType = model.SortingType.Value;
                    }

                    //making sure null is not passed into the service method
                    parameters.Formats = model.FormatsFilter == null ? null : new List<int>() { model.FormatsFilter.Value };
                    parameters.Languages = model.LanguagesFilter == null ? null : new List<int>() { model.LanguagesFilter.Value };
                    parameters.Authors = model.AuthorsFilter == null ? null : new List<int>() { model.AuthorsFilter.Value };
                    parameters.Publishers = model.PublishersFilter == null ? null : new List<int>() { model.PublishersFilter.Value };





                    var dto = _businessService.GetPageADO(parameters);
                    if (!dto.isOK)
                    {
                        return RedirectToAction("Error", "Home");
                    }

                    QueryResultWrapper result = dto.data;

                    //Fill the ViewModel with new data

                    model.MinPrice = result.MinPrice;
                    model.MaxPrice = result.MaxPrice;
                    model.Authors = result.Authors;
                    model.Formats = result.Formats;
                    model.Languages = result.Languages;
                    model.Products = result.Products;
                    model.Publishers = result.Publishers;
                    model.ResultCount = result.ResultCount;
                    model.MaxPriceFilter = model.MaxPriceFilter ?? model.MaxPrice;
                    model.MinPriceFilter = model.MinPriceFilter ?? model.MinPrice;
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
            }
            catch (Exception e)
            {
                return AlzaError.ExceptionActionResult(e);
            }

        }
    }
}

TestWeb/Views/Order/Cart.cshtml
@using Eshop2.Models.OrderViewModels
@using Trainee.Business.DAL.Entities
@inject SignInManager<ApplicationUser> SignInManager;
@model CartViewModel
@{
    ViewData["Title"] = "Košík";
}

@{
    decimal totalPrice = 0;
    foreach (CartItem c in Model.Cart)
    {

        totalPrice += c.Product.Price * c.Amount;

    }
}

<h2>@ViewData["Title"]</h2>


@{if (ViewData["emptyCart"] != null)
    {
        <div class="row empty-cart">
            <p class="text-center">Ještě tu není žádná knížka.</p>
            <h4 class="text-center"><a asp-controller="Catalogue" asp-action="Products" asp-route-id="1">Vyrazte nakupovat!</a></h4>

            <div class="col-md-6 text-center"><img src="~/images/coolbooks.jpg" alt="cool books" /></div>
            <div class="col-md-6 text-center"><img src="~/images/needbook.png" alt="need a book?" /></div>
        </div>
    }

    else

    {
        <div id="cart-wrapper">


            @foreach (CartItem c in Model.Cart)
            {
                <div class="row cart-item bottom-padding">
                    <a asp-controller="catalogue" asp-action="book" asp-route-id="@c.ProductId">
                        <div class="col-md-1 no-padding hidden-sm hidden-xs">
                            <img src="~/images/product_images/@c.Product.PicAddress" alt="bookcover" />
                        </div>
                        <div class="col-md-4">
                            <p><strong>@c.Product.Name</strong></p>

                            <input type="hidden" class="product-id-hidden" value="@c.ProductId" />

                            <p>
                                @{
                                    var a = c.Product.Book.AuthorsBooks;
                                    for (int i = 0; i < a.Count; i++)
                                    {

                                        @a[i].Author.Name @Html.Raw(" ") @a[i].Author.Surname

                                        @if (i != a.Count - 1)
                                        {@Html.Raw(", ")}
                                    }
                                }
                            </p>
                        </div>
                    </a>
                    <div class="col-md-2 responsive-cart">
                        <p>@c.Product.State.Name</p>

                    </div>
                    <div class="col-md-2 responsive-cart unselectable">
                        <span class="glyphicon glyphicon-minus product-count-decrease"></span>
                        <input type="number" class="product-count" value="@c.Amount" min="1" />
                        <span class="glyphicon glyphicon-plus product-count-increase"></span>
                        <input type="hidden" class="product-count-original" value="@c.Amount" />
                        <input type="hidden" class="product-count-prevalidation" value="@c.Amount" />

                    </div>

                    <div class="col-md-2 responsive-cart">
                        <input type="hidden" class="product-price-hidden" value="@c.Product.Price" />

                        @String.Format("{0:c}", c.Product.Price)
                    </div>
                    <div class="col-md-1 responsive-cart"><a><span class="glyphicon glyphicon-remove remove"></span><span class="sr-only">Smazat</span></a></div>
                </div>

                                    }
        </div>

        <hr class="bottom-padding" />


        <div class="row bottom-padding text-right total-price">
            <p>
                Celková cena:<span id="total-price-string"> @String.Format("{0:c}", totalPrice)</span>
            </p>
        </div>


        <div class="row">
            <div class="col-md-6 order-buttons-div">
                <a class="btn btn-default" asp-controller="catalogue" asp-action="products"><span class="glyphicon glyphicon-menu-left triangle-left"></span>Nakupovat dál</a>
            </div>
            <div class="col-md-6 bottom-padding">
                @if (SignInManager.IsSignedIn(User))
                {
                    
                    <a class="btn btn-prim order-button" asp-controller="Order" asp-action="Order">Objednat<span class="glyphicon glyphicon-menu-right triangle-right"></span></a>
                }
                else
                {
                    <a class="btn btn-prim order-button" asp-controller="Order" asp-action="OrderLogin">Objednat<span class="glyphicon glyphicon-menu-right triangle-right"></span></a>
                }
            </div>
        </div>
                                    }
}

TestWeb/Views/Order/OKPage.cshtml
@using Eshop2.Models.OrderViewModels
@using Trainee.Core.DAL.Entities
@using Trainee.Business.DAL.Entities
@model OrderViewModel
@{
    ViewData["Title"] = "Objednávka úspěšná";
}
<h2>Objednávka odeslána</h2>

<h3 class="text-indent">Děkujeme!</h3>
<p class="text-indent">Objednávku s číslem #@ViewData["OrderId"] jsme v pořádku přijali. Můžete se začít těšit na nové knížky.</p>

TestWeb/Views/Order/Order.cshtml
@using Eshop2.Models.OrderViewModels
@using Trainee.Core.DAL.Entities
@using Trainee.Business.DAL.Entities
@model OrderViewModel
@{
    ViewData["Title"] = "Objednávka";
    decimal orderPrice = 0;
}



<h2>@ViewData["Title"]</h2>

<h3 class="bottom-padding">Vybrané knížky</h3>
<div class="order-items">
    <div class="row order-items-heading hidden-sm hidden-xs">
        <div class="col-md-4">Název knihy</div>
        <div class="col-md-4">Autor</div>
        <div class="col-md-1">Počet</div>
        <div class="col-md-3">Celková cena</div>
    </div>


    @{
        foreach (CartItem c in Model.Items)
        {
            <div class="row order-items-row">
                <div class="col-md-4">
                    <p class="order-book-name">@c.Product.Name</p>
                </div>
                <div class="col-md-4">
                    <p>
                        @{
                            var a = c.Product.Book.AuthorsBooks;
                            for (int i = 0; i < a.Count; i++)
                            {

                                @a[i].Author.Name @Html.Raw(" ") @a[i].Author.Surname

                                @if (i != a.Count - 1)
                                {@Html.Raw(", ")}
                            }
                        }
                    </p>
                </div>
                <div class="col-md-1">
                    @c.Amount ks
                </div>
                <div class="col-md-3">
                    @{
                        decimal booksPrice = 0;
                        {

                            booksPrice += c.Product.Price * c.Amount;

                        }
                    }

                    @String.Format("{0:c}", booksPrice)
                </div>
            </div>
                            orderPrice += booksPrice;
                        }

    }
    <div class="row order-price"><p class="text-right">Cena objednávky: @String.Format("{0:c}", orderPrice)</p></div>   
    
</div>



<h3>Dodací údaje</h3>
<div class="form-group">
    <form asp-action="Order" asp-controller="Order" asp-route-returnurl="@ViewData["ReturnUrl"]" onsubmit="return isChecked()" method="post">
        <div class="order">
            <div class="row bottom-padding">
                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="row form-row">
                    <div class="col-md-6 responsive-col">
                        <label class="text-indent control-label" asp-for="Name"></label>
                        <input class="form-control" asp-for="Name" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 responsive-col">
                        <label class="text-indent control-label" asp-for="Surname"></label>
                        <input class="form-control" asp-for="Surname" />
                        <span asp-validation-for="Surname" class="text-danger"></span>
                    </div>
                </div>
                <div class="row form-row">
                    <div class="col-md-6 responsive-col">
                        <label class="text-indent control-label" asp-for="Email"></label>
                        <input class="form-control" asp-for="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 responsive-col">
                        <label class="text-indent control-label" asp-for="Phone"></label>
                        <input class="form-control" asp-for="Phone" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                </div>

                <div class="row form-row">
                    <div class="col-md-6 responsive-col">
                        <label class="text-indent control-label" asp-for="Street"></label>
                        <input class="form-control" asp-for="Street" />
                        <span asp-validation-for="Street" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 responsive-col">
                        <label class="text-indent control-label" asp-for="PostalCode"></label>
                        <input class="form-control" asp-for="PostalCode" />
                        <span asp-validation-for="PostalCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="row form-row">
                    <div class="col-md-6 responsive-col">
                        <label class="text-indent control-label" asp-for="City"></label>
                        <input class="form-control" asp-for="City" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>

                    <div class="col-md-6 responsive-col">
                        <label class="text-indent control-label" asp-for="CountryId"></label>
                        <select class="form-control" asp-for="CountryId">
                            <option selected disabled>Zvolte zemi...</option>
                            @{
                                foreach (Country c in Model.Countries)
                                {

                                    {
                                        
                                        @if (c.Id == 1)
                                        {
                                            <option class="option-cs" value="@c.Id">@c.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@c.Id">@c.Name</option>
                                        }
                                    }
                                }
                            }

                        </select>
                    </div>

                </div>
            </div>

            <div class="row bottom-padding">
                <div class="col-md-6 responsive-col">
                    <strong class="text-indent">Doprava</strong><br />

                    @{
                        foreach (Shipping s in Model.Shipping)
                        {
                            <div class="radio order-radio">
                                <input type="radio" value="@s.Id" asp-for="ShippingId" /> @s.Name @Html.Raw(" | ") @String.Format("{0:c}", s.Price)<br />
                            </div>
                        }
                    }
                </div>
                <div class="col-md-6 responsive-col">
                    <strong class="text-indent">Platba</strong><br />

                    @{
                        foreach (Payment p in Model.Payment)
                        {
                            <div class="radio order-radio">
                                <input type="radio" value="@p.Id" asp-for="PaymentId" /> @p.Name <br />
                            </div>
                        }
                    }

                </div>
            </div>
            <div class="row text-left bottom-padding">
                <input type="checkbox" id="naughty-checkbox" asp-for="IsChecked" /> Souhlasím s <a asp-controller="Home" asp-action="Conditions">Obchodními podmínkami.</a>
                <div class="checkbox-error text-danger"><p>Prosím potvrďte souhlas s obchodními podmínkami.</p></div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6 order-buttons-div">
                <a class="btn btn-default" asp-controller="Order" asp-action="Cart"><span class="glyphicon glyphicon-menu-left triangle-left"></span>Zpět do košíku</a>
            </div>
            <div class="col-md-6 bottom-padding">
                <button class="btn btn-prim order-button" type="submit">Objednat<span class="glyphicon glyphicon-menu-right triangle-right"></span></button>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TestWeb/Views/Order/OrderLogin.cshtml
@using Eshop2.Models.OrderViewModels

@{
    ViewData["Title"] = "Přihlášení k objednávce";

    ViewData["ReturnUrl"] = "/Order/Redirect";
}

<h2>Chcete se přihlásit?</h2>

<div class="row orderlogin">
    <div class="col-md-6 partiallogin">
        @Html.Partial("~/Views/Shared/_LoginPartial.cshtml", new LoginViewModel(), ViewData)
    </div>
    <div class="col-md-6">
        <div class="row text-center register-container">
            <a asp-controller="Account" asp-action="Register" asp-route-returnurl="@ViewData["ReturnUrl"]">
                <div class="col-md-6"><img src="~/images/add-user.svg" /></div>
                <div class="col-md-6"><p>Nemáte účet? Zaregistrujte se</p></div>
            </a>
        </div>

        <div class="row text-center register-container">
            <a asp-controller="Order" asp-action="Order">
                <div class="col-md-6"><img src="~/images/fast-order.svg" /></div>
                <div class="col-md-6"><p>Nakoupit bez registrace</p></div>
            </a>
        </div>
    </div>

</div>

TestWeb/Views/Order/Redirect.cshtml
@{
    ViewData["Title"] = "Přesměrování";
}

<div class="redirect">
    <a asp-action="Order" asp-controller="Order" class="redirection">Přesměrováváme Vás na objednávku...</a>
</div>

TestWeb/Views/Order/Summary.cshtml
@using Eshop2.Models.OrderViewModels
@using Trainee.Core.DAL.Entities
@using Trainee.Business.DAL.Entities
@model OrderViewModel

@{
    ViewData["Title"] = "Rekapitulace";
    decimal productsPrice = 0;


    foreach (CartItem c in Model.Items)
    {
        productsPrice += c.Amount * c.Product.Price;
    }

    decimal totalPrice = productsPrice;
}


<h2>@ViewData["Title"]</h2>

<div class="order-items">
    <div class="row order-items-heading hidden-sm hidden-xs">
        <div class="col-md-4">Název knihy</div>
        <div class="col-md-4">Autor</div>
        <div class="col-md-1">Počet</div>
        <div class="col-md-3">Cena</div>
    </div>


    @{
        foreach (CartItem c in Model.Items)
        {
            <div class="row order-items-row">
                <div class="col-md-4">
                    <p class="order-book-name">@c.Product.Name</p>
                </div>
                <div class="col-md-4">
                    <p>
                        @{
                            var a = c.Product.Book.AuthorsBooks;
                            for (int i = 0; i < a.Count; i++)
                            {

                                @a[i].Author.Name @Html.Raw(" ") @a[i].Author.Surname

                                @if (i != a.Count - 1)
                                {@Html.Raw(", ")}
                            }
                        }
                    </p>
                </div>
                <div class="col-md-1">
                    @c.Amount ks
                </div>
                <div class="col-md-3">
                    @{
                        decimal booksPrice = 0;
                        {

                            booksPrice += c.Product.Price * c.Amount;
                            productsPrice += booksPrice;

                        }
                    }

                    @String.Format("{0:c}", booksPrice)
                </div>
            </div>
                        }

    }

</div>

    <div class="row summary-div bottom-padding">
        <div class="col-md-6">
            <p><strong>Dodací údaje</strong></p>
            <p>
                Jméno: @Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Surname)<br />
                E-mail: @Html.DisplayFor(model => model.Email) <br />
                Telefon: @Html.DisplayFor(model => model.Phone)<br /><br />
                Ulice a č.p.: @Html.DisplayFor(model => model.Street)<br />
                Město: @Html.DisplayFor(model => model.City)<br />
                PSČ: @Html.DisplayFor(model => model.PostalCode)<br />
                Země: @Html.DisplayFor(model => model.Countries[0].Name)
            </p>
        </div>
        <div class="col-md-6 summary-shipping">
            <strong>Doprava</strong><br />

            @{
                foreach (Shipping s in Model.Shipping)
                {
                    <div class="radio text-indent">
                        <input type="radio" value="@s.Id" asp-for="ShippingId" /> @s.Name - @String.Format("{0:c}" ,s.Price)<br />
                    </div>

                    totalPrice += s.Price;
                }
            }
            <strong>Platba</strong><br />


            @{
                foreach (Payment p in Model.Payment)
                {
                    <div class="radio text-indent">
                        <input type="radio" value="@p.Id" asp-for="PaymentId" /> @p.Name <br />
                    </div>
                }
            }

            <strong>Celková cena </strong>
            <p class="bold text-indent">@String.Format("{0:c}", @totalPrice)</p>

        </div>
    </div>

@*Data to pass on*@

<form method="post">
    <input type="hidden" asp-for="IsChecked"/>
    <input type="hidden" asp-for="Name" />
    <input type="hidden" asp-for="Surname" />
    <input type="hidden" asp-for="Email" />
    <input type="hidden" asp-for="Phone" />
    <input type="hidden" asp-for="Street" />
    <input type="hidden" asp-for="City" />
    <input type="hidden" asp-for="PostalCode" />
    @{
        foreach (Country c in Model.Countries)
        {
            <input type="hidden" value="@c.Id" asp-for="CountryId">
        }
    }

    @{
        foreach (Shipping s in Model.Shipping)
        {
            <input type="hidden" value="@s.Id" asp-for="ShippingId" />
        }
    }

    @{
        foreach (Payment p in Model.Payment)
        {
            <input type="hidden" value="@p.Id" asp-for="PaymentId" />
        }
    }

    <div class="row">
        <div class="col-md-6 order-buttons-div">
            <button asp-action="BackToOrder" asp-controller="Order" asp-route-returnurl="@ViewData["ReturnUrl"]" asp-route-route="false" class="btn btn-default" type="submit"><span class="glyphicon glyphicon-menu-left triangle-left"></span>Změnit</button>
        </div>
        <div class="col-md-6 bottom-padding">
            <button asp-action="SendOrder" asp-controller="Order" asp-route-returnurl="@ViewData["ReturnUrl"]" asp-route-route="false" class="btn btn-prim order-button" type="submit">Potvrdit<span class="glyphicon glyphicon-send triangle-right"></span></button>
        </div>
    </div>

</form>