TestWeb/Models/HomeViewModels/ShippingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Trainee.Business.DAL.Entities;

namespace Eshop2.Models.HomeViewModels
{
    public class ShippingViewModel
    {
        public List<Shipping> Shipping { get; set; }
        public List<Payment> Payment { get; set; }
    }
}

TestWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Eshop2.Models.HomeViewModels;
using Trainee.Business.Business;
using Trainee.Business.DAL.Entities;
using TestWeb.Models.HomeViewModels;

namespace TestWeb.Controllers
{
    /// <summary>
    /// This is a home controller providing basic data
    /// </summary>
    public class HomeController : Controller
    {
        private readonly OrderService _orderService;
        private readonly BusinessService _businessService;

        public HomeController(OrderService ordServ, BusinessService busServ)
        {
            _orderService = ordServ;
            _businessService = busServ;
        }

        //GET: /Home/Index
        public IActionResult Index()
        {
            var result = _businessService.GetPageSlots();
            Dictionary<int,FrontPageSlot> items;
            items = result.isOK ? result.data : new Dictionary<int, FrontPageSlot>();
            IndexViewModel model = new IndexViewModel { Slots = items };
            return View(model);
        }

        //GET: /Home/About
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        //GET: /Home/Contact
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        //GET: /Home/Conditions
        public IActionResult Conditions()
        {
            return View();
        }

        //GET: /Home/Shipping
        public IActionResult Shipping()
        {

            ShippingViewModel model = new ShippingViewModel();

            var resultShipping = _orderService.GetShippings();
            if (!resultShipping.isOK)
                return RedirectToAction("Error");
            model.Shipping = resultShipping.isEmpty ? new List<Shipping>() : resultShipping.data;

            var resultPayment = _orderService.GetPayments();
            if (!resultPayment.isOK)
                return RedirectToAction("Error");
            model.Payment = resultPayment.isEmpty ? new List<Payment>() : resultPayment.data;

            return View(model);
        }

        //GET: /Home/Error
        public IActionResult Error()
        {
            return View();
        }
    }
}

TestWeb/ViewComponents/FrontpageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Trainee.Business.Business;
using Trainee.Business.Business.Enums;
using Trainee.Business.DAL.Entities;

namespace Eshop2.ViewComponents
{
    public class FrontpageViewComponent : ViewComponent
    {
        BusinessService _service;
        public FrontpageViewComponent(BusinessService service)
        {
            _service = service;
        }
        public async Task<IViewComponentResult> InvokeAsync(FrontPageItem item)
        {
            FrontPageParameter param = (FrontPageParameter)Enum.Parse(typeof(FrontPageParameter), item.FrontPageParameter, true);
            SortType type = (SortType)Enum.Parse(typeof(SortType), item.SortType, true);
            
            var res = _service.GetFrontPage(param , type, item.Count, item.CategoryId, item.TimeOffSet);
            var data = res.data;
            return View(data);

        }
    }
}

TestWeb/Views/Home/About.cshtml
@using Trainee.Core.DAL.Entities
@model EditViewModel
@{
    ViewData["Title"] = "Profil uživatele";
}

<script type="text/javascript">
    function showStuff(id, text, btn) {
        document.getElementById(id).style.display = 'block';
        // hide the lorem ipsum text
        document.getElementById(text).style.display = 'none';
        // hide the link
        btn.style.display = 'none';
    }
</script>

<div class="container">
    <div class="row row-centered profile">

        <div id="slip">
            <div class="col-lg-5 profile-left">
                <h2>Adam Bílý</h2>
                <div class="col-lg-6 profile-info">
                    <p class="profile-item">E-mail:</p>
                    <p class="profile-item">Adresa:</p>
                    <p class="profile-item">Město:</p>
                    <p class="profile-item">PSČ:</p>
                    <p class="profile-item">Země:</p>
                </div>
                <div class="col-lg-6">
                    <p class="second">email@email.cz</p>
                    <p class="second">Alzákova 582</p>
                    <p class="second">Praha</p>
                    <p class="second">110 00</p>
                    <p class="second">Česko</p>
                </div>
            </div>


            <div class="col-lg-4 profile-right">
                <img src="https://www.itnetwork.cz/images/avatars/29878.png?v=1494148410" alt="profile-photo" class="img-fluid img-profile" /><br />
                <button type="button" onclick="showStuff('change', 'slip');" class="btn btn-success btn-profile">Změnit údaje</button>
            </div>
        </div>

        <div id="change" style="display: none;">
            <div class="col-lg-10 profile-left">
                <h2>Změna údajů:</h2>
                <form>
                    <div class="row form-row">
                        <div class="col-lg-4">
                            <label class="text-indent control-label" asp-for="Name"></label>
                            <input class="form-control" asp-for="Name" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="col-lg-4">
                            <label class="text-indent control-label" asp-for="Surname"></label>
                            <input class="form-control" asp-for="Surname" />
                            <span asp-validation-for="Surname" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="col-lg-8">
                            <label class="text-indent control-label" asp-for="Street"></label>
                            <input class="form-control" asp-for="Street" />
                            <span asp-validation-for="Street" class="text-danger"></span>
                        </div>
                        <div class="col-lg-6">
                            <label class="text-indent" asp-for="Country">Stát</label>
                            <select class="form-control" asp-for="CountryCode">
                            <!-- In case of remaking layout dont change this foreach loop-->
                                @{
                                    foreach (Country c in Model.Countries)
                                    {
                                        <option value="@c.CountryCode">@c.Name</option>
                                    }
                                }

                            </select>
                            <span asp-validation-for="Country" class="text-danger"></span>
                        </div>
                        <div class="col-lg-6">
                            <label class="text-indent" asp-for="City">Město</label>
                            <input class="form-control" asp-for="City" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="text-small"><small id="fileHelp" class="form-text text-muted">Pole, do kterých nevložíte žádná data se nezmění.</small></div>
                    </div>
                </form>
                <div class="col-lg-10 change-top">
                    <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                    <small id="fileHelp" class="form-text text-muted">Velikost souboru může být maximálně 4MB</small><br />
                    <button type="submit" class="btn btn-success btn-profile">Uložit</button>
                    <button type="button" onclick="showStuff('slip', 'change');" class="btn btn-danger btn-profile">Zrušit</button>
                </div>
                </div>
            </div>

    </div>

    <!--

    <div class="col-lg-10"><hr class="body-line" /></div>

    <div class="col-lg-10 cart-items">
        <h2>Můj košík:</h2>
    </div>

    <div class="col-lg-10"><hr class="body-line" /></div>

    <div class="col-lg-10 cart">
        <h2>Mé objednávky:</h2>
    </div>-->

</div>

TestWeb/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Kontakty";
}


<h2 class="title-register">@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-6">
        <p><strong>Fantastic Books s.r.o.</strong></p>
        <p>Guttenbergova 272/5<br />
        460 02 Liberec<br />
        +420 531 648 523<br />
            <a href="mailto:ahoj@fantasticbooks.cz">ahoj@fantasticbooks.cz</a></p>

        <p>IČ: 285 64 952<br />
        DIČ: CZ54882056<br />
        Zapsáno u Městského soudu v Liberci, vložka B 587/13.
        </p>
    </div>

    <div class="col-md-6">
        <div class="map">
            <iframe src="https://api.mapy.cz/frame?params=%7B%22x%22%3A15.06083208684987%2C%22y%22%3A50.76873265433182%2C%22base%22%3A%2227%22%2C%22layers%22%3A%5B%5D%2C%22zoom%22%3A16%2C%22url%22%3A%22https%3A%2F%2Fmapy.cz%2Fs%2F1YRxk%22%2C%22mark%22%3A%7B%22x%22%3A%2215.06202298765247%22%2C%22y%22%3A%2250.76870720879364%22%2C%22title%22%3A%22Gutenbergova%20272%2F5%2C%20Liberec%22%7D%2C%22overview%22%3Afalse%7D&amp;width=500&amp;height=333&amp;lang=cs" width="100%" height="100%" style="border:none" frameBorder="0"></iframe>
        </div>
    </div>
</div>

TestWeb/Views/Home/Index.cshtml
@using TestWeb.Models.HomeViewModels
@using Trainee.Business.DAL.Entities
@using Trainee.Catalogue.DAL.Entities
@using Trainee.Business.Business.Enums
@model IndexViewModel
@{
    ViewData["Title"] = "Home Page";
}

@{ 
    FrontPageItem item = Model.Slots[1].Item;
}
<img class="front-image img-responsive" src="~/images/frontpic.png" alt="front picture" />
<h2>@item.Name</h2>

<div class="row">
    @await Component.InvokeAsync("Frontpage", new { item = item})
</div>

@{
    item = Model.Slots[2].Item;
}
<h2>@item.Name</h2>

<div class="row">
    @await Component.InvokeAsync("Frontpage", new { item = item })
</div>
<div class="index-commercial">
    <img src="~/images/index-commercial.png" alt="book commercial" />
</div>
@{
    item = Model.Slots[3].Item;
}
<h2>@item.Name</h2>

<div class="row">
    @await Component.InvokeAsync("Frontpage",  new { item = item })
</div>

TestWeb/Views/Home/Shipping.cshtml
@using Eshop2.Models.HomeViewModels;
@using Trainee.Business.DAL.Entities;

@model ShippingViewModel
@{ 
    ViewData["Title"] = "Doprava a platba";
}

<h2>@ViewData["Title"]</h2>

<h3>Doprava</h3>

Podle vaší polohy v galaxii a finančních možností můžete zvolit následující způsoby dopravy:
<ul>
    @foreach (Shipping s in Model.Shipping)
    {
        <li>@s.Name - @String.Format("{0:c}", s.Price)</li>
    }
</ul>

<h3>Platba</h3>

<ul>
    @foreach (Payment p in Model.Payment)
    {
        <li>@p.Name</li>
    }
</ul>